# Generated by Django 4.0.4 on 2022-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size_metric',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=180),
        ),
    ]
