# Generated by Django 4.0.5 on 2022-06-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_is_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='page_url',
            field=models.CharField(max_length=280),
        ),
    ]
