version: '3.8'
services: 
    api:
        build: ./api/
        volumes: 
            - ./api/:/app
        command: gunicorn api.wsgi:application --bind 0.0.0.0:8000 --timeout 0
        ports: 
            - 8000:8000
        env_file:
            - ./api/.env

    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    
    # nginx:
    #     build: ./nginx
    #     # volumes:
    #     #     - static_volume:/home/app/web/staticfiles
    #     ports:
    #         - 80:80
    #     depends_on:
    #         - api
