name: Grupohuno backend CI/CD

# triggers for our workflow
on:
  pull_request:
    branches:
      - develop
      - master
  
  push:
    branches:
      - master
      - develop

# Three job definition
jobs:
  health-check-job: # Testing and code formatting check
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    # env:
    #   SECRET_KEY: sfaf
    #   DJANGO_SETTINGS_MODULE: api.settings
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Create env file"
        run: |
          touch .env
          echo SECRET_KEY={{ secrets.SECRET_KEY }} >> .env
          echo DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }} >> .env
      - name: "Install Dependencies"
        run: make build
      - name: "Check Code Format"
        run: make pylint
      - name: "Test Code"
        run: make supertest