name: Grupohuno backend CI/CD

# triggers for our workflow
on:
  pull_request:
    branches:
      - develop
      - master
  
  push:
    branches:
      - master
      - develop

# Three job definition
jobs:
  health-check-job: # Testing and code formatting check
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Create env file"
        run: |
          touch .env
          echo SECRET_KEY={{ secrets.SECRET_KEY }} >> .env
          echo DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }} >> .env
          echo POSTGRES_NAME=${{ secrets.POSTGRES_NAME }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
      - name: "Install Dependencies"
        run: make build
      - name: "Check Code Format"
        run: make pylint
      - name: "Test Code"
        run: make supertest